[project]
name = "hexlet-hello-world"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "more-itertools>=10.8.0",
]

[dependency-groups]
dev = [
    "black>=25.1.0",
    "ruff>=0.12.12",
]
